HACKERRANK MEDIUM QUESTION 

APPROACH 1:--(MAKE ALL SUCH TYPE OF MATRIX SATISFYING THE SAID CONDITION AND THEN SUBTRACT THERE SUM WITH
THE GIVEN MATRIX SUM AND GIVE THE MINIMUM ANS OF SUM FROM ALL SUCH MATRIXES

......code will be uploaded soon.......
